@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWFjYXN0cm8iLCJpYXQiOjE3MzU3NDM3NTksImV4cCI6MTczNTc0NzM1OX0.79kX_XR-XmVngzXtkuY4Z3ZRPFF3PcYPm8lht6Oc6X0
@token2 = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWF0cml6YyIsImlhdCI6MTczNTc0Mzc3NCwiZXhwIjoxNzM1NzQ3Mzc0fQ._4sxb3kojrfAxTZxU_kFhOyvo7K9AfI2s_ApEfKXkgo

////////// AUTH ENDPOINT //////////
// SignIn: Anyone
POST {{baseUrl}}/auth/signIn
Content-Type: application/json

# {
#   "username": "beacastro",
#   "password": "secret"
# }
{
  "username": "beatrizc",
  "password": "secret"
}
###

// SignUp: Anyone
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

# {
#   "username": "beacastro",
#   "password": "secret"
# }
{
  "username": "beatrizc",
  "password": "secret"
}
###

////////// POST ENDPOINT //////////
// fetchAll: Anyone
GET {{baseUrl}}/posts
###

// fetchById: Anyone
GET {{baseUrl}}/posts/123
###

// Create: Admin
POST {{baseUrl}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Title Example TWO",
  "description": "A long description example. Example TWO A long description example. Example TWO A long description example. Example TWO"
}
###

// Update: Admin
PUT {{baseUrl}}/posts/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Title Example 02",
  "description": "Another example 02"
}
###

// Delete: Admin
DELETE {{baseUrl}}/posts/2
Authorization: Bearer {{token}}
###

// fetchAllComments: Anyone
GET {{baseUrl}}/posts/{id}/comments
###

// CreateComments: Anyone logado
POST {{baseUrl}}/posts/{id}/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "Comment Example 01",
}
###

// UpdateComments: CommentOwner
PUT {{baseUrl}}/posts/{id}/comments/{commentId}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "Comment Example 02",
}
###

// DeleteComments: CommentOwner, admin
DELETE {{baseUrl}}/posts/{id}/comments/{commentId}
Authorization: Bearer {{token}}
###

////////// USER ENDPOINT //////////
// fetchAll: Admin
GET {{baseUrl}}/users
Authorization: Bearer {{token}}
###

// setIsAdmin: Admin
PATCH {{baseUrl}}/users/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "isAdmin": true
}
###

////////// STORAGE ENDPOINT //////////
// download: Anyone
GET {{baseUrl}}/storage/2b0c
# GET {{baseUrl}}/storage/{imageName}
###

// upload: Admin
POST {{baseUrl}}/storage
# POST {{baseUrl}}/storage/{imageName}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=B

--B
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ../static/f852.png
--B-
###

