@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWFjYXN0cm8iLCJpYXQiOjE3MzU5MTMxNzEsImV4cCI6MTczNTkxNjc3MX0.JCbuSXiCDuDpyMTEYEdr4zp15RYB5xtWTNcFaBfarLk
@token2 = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWF0cml6Y1NUQU5EIiwiaWF0IjoxNzM1OTEzMTk2LCJleHAiOjE3MzU5MTY3OTZ9.61JuzTBZncEPyeekG0qOZ5YqlGjPqGPiPoCfhBx3Gd4

////////// AUTH ENDPOINT //////////
// SignIn: Anyone
POST {{baseUrl}}/auth/signIn
Content-Type: application/json

# {
#   "username": "beacastro",
#   "password": "secret"
# }
{
  "username": "beatrizcSTAND",
  "password": "secret"
}
###

// SignUp: Anyone
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

# {
#   "username": "beacastro",
#   "password": "secret"
# }
{
  "username": "beatrizcSTAND",
  "password": "secret"
}
###

////////// POST ENDPOINT //////////
// fetchAll: Anyone
GET {{baseUrl}}/posts
###

// fetchById: Anyone
GET {{baseUrl}}/posts/8
###

// Create: Admin
POST {{baseUrl}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Title Example 12",
  "description": "Example 12 A long description example. Example 12 A long description example. Example 12 A long description example. Example 12"
}
###

// Update: Admin
PUT {{baseUrl}}/posts/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
"title": "Title Example 05",
  "description": "Example 05 A long description example. Example 05 A long description example. Example 05 A long description example. Example 05"
}
###

// Delete: Admin
DELETE {{baseUrl}}/posts/8
Authorization: Bearer {{token}}
###

// fetchAllComments: Anyone
GET {{baseUrl}}/posts/12/comments
###

// CreateComments: Anyone logado
POST {{baseUrl}}/posts/11/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "Criando um comentario pelo vs api novamente"
}
###

// UpdateComments: CommentOwner
PUT {{baseUrl}}/posts/11/comments/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "My comment #1"
}
###

// DeleteComments: CommentOwner, admin
DELETE {{baseUrl}}/posts/11/comments/9
Authorization: Bearer {{token}}
###

////////// USER ENDPOINT //////////
// fetchAll: Admin
GET {{baseUrl}}/users
Authorization: Bearer {{token}}
###

// setIsAdmin: Admin
PATCH {{baseUrl}}/users/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "isAdmin": true
}
###

////////// STORAGE ENDPOINT //////////
// download: Anyone
GET {{baseUrl}}/storage/2b0c
# GET {{baseUrl}}/storage/{imageName}
###

// upload: Admin
POST {{baseUrl}}/storage
# POST {{baseUrl}}/storage/{imageName}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=B

--B
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ../static/11.png
--B-
###

